# Generated by Django 3.2.7 on 2021-09-10 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Userotp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_st', models.DateTimeField(auto_now=True)),
                ('otp', models.SmallIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=15, null=True)),
                ('lname', models.CharField(blank=True, max_length=15, null=True)),
                ('profileimg', models.ImageField(blank=True, default='user.png', null=True, upload_to='')),
                ('age', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('profession', models.CharField(blank=True, max_length=25, null=True)),
                ('specialization', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=25, null=True)),
                ('city', models.CharField(blank=True, max_length=25, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
